name: quiz_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  hexcolor: ^3.0.1
  image_picker: ^1.1.2
  path: ^1.9.0
  provider: ^6.1.2
  shared_preferences: ^2.3.1
  video_player: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/asset/video/HACA.mp4
    - lib/asset/image/bg.jpg
    - lib/asset/image/Asset 2@4x.png
    - lib/asset/image/15204.jpg
